import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { manrope } from "@/lib/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} relative no-scrollbar scroll-smooth`}
      >
        <>
          <Navbar />
          <div className="grow">{children}</div>
        </>
      </body>
    </html>
  );
}
